window_manager = "hyprland"

[connection]
host = "localhost"
port = 4455
password = ""

[obs]
scenes = [] # selects all scenes

[monitors.DVI-D-1]
show = "Right monitor"
hide = "Left monitor"

[monitors.HDMI-A-1]
show = "Left monitor"
hide = "Right monitor"
